version: '3'

services:
  streamlit:
    container_name: frontend
    image: diapricepred
    build:
        context: .
        dockerfile: src/diamond_price_prediction/frontend/Dockerfile
    command: ["python","-m","streamlit", "run", "src/diamond_price_prediction/frontend/dashboard.py"]
    ports:
      - 8501:8501
    # depends_on:
    #   - fast_api
    # volumes:
    #     - .:/app

  fast_api:
    container_name: backend
    image: diapricepred
    build:
        context: .
        dockerfile: src/diamond_price_prediction/backend/Dockerfile
    command: sh -c "uvicorn src.diamond_price_prediction.backend.application:app --host 0.0.0.0 --port 9080 --reload"
    ports:
      - 9080:9080
    # volumes:
    #     - .:/app
